<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FileCrypter.Desktop</AssemblyName>
    <RootNamespace>FileCrypter.Desktop</RootNamespace>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\FileCrypter.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <UsedAvaloniaProducts></UsedAvaloniaProducts>
    <UseAppHost Condition="'$(Configuration)' == 'Debug'">false</UseAppHost>
    <Version>0.1.0</Version>
    <MacBundleName>FileCrypter</MacBundleName>
    <MacBundleDisplayName>FileCrypter</MacBundleDisplayName>
    <MacBundleIdentifier>com.novafluxx.filecrypter</MacBundleIdentifier>
    <MacMinimumSystemVersion>13.0</MacMinimumSystemVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileCrypter.Core\FileCrypter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
</Project>
